name: logging_manager
description: Provides simple APIs for logging & managing logs. Uses the logger from the logging package.
version: 1.0.0+1
repository: https://github.com/predatorx7/flutter_packages
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  meta: ^1.3.0
  logging: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
