name: logging_manager
description: Provides simple APIs for logging & managing logs. Uses the logger from the logging package.
version: 2.2.2+1
repository: https://github.com/predatorx7/flutter_packages
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.0
  meta: ^1.3.0
  logging: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
