name: relaxed_client
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  fimber: ^0.6.1
  http: ^0.13.3
  

dev_dependencies:
  rational_lint: ^1.0.0
  test: ^1.14.4
dependency_overrides:
  rational_lint:
    path: ../rational_lint