name: youtube_players
description: A Flutter package which provides various youtube players depending on your requirement
version: 0.2.0
repository: https://github.com/predatorx7/flutter_packages.git 

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  android_intent: ^2.0.2
  flutter:
    sdk: flutter
  logging: ^1.0.1
  url_launcher: ^6.0.6
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
