name: youtube_players
description: A new Flutter package project.
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  android_intent: ^2.0.2
  flutter:
    sdk: flutter
  logging: ^1.0.1
  url_launcher: ^6.0.6
  webview_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  rational_lint: ^1.0.0

dependency_overrides:
  rational_lint:
    path: ../rational_lint
