name: rational_lint
version: 1.0.0
description: A heavily strict analysis_options for Dart/Flutter projects with strict lint rules
repository: https://gitlab.com/binarynumbers/rational_lint
issue_tracker: https://gitlab.com/binarynumbers/rational_lint/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
