name: magnific_ui
description: Extra flutter UI components that every app might be need
version: 0.4.0
repository: https://github.com/predatorx7/flutter_packages.git
 
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
