name: app_boot
description: LaunchScreen & a dart flavor settings manager required for starting an app with settings.
version: 0.3.0
homepage: https://magnificsoftware.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter:
