name: app_boot
description: LaunchScreen & a flutter flavor/app manager required for starting an app with settings.
version: 0.2.2
homepage: https://magnificsoftware.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  freezed: ^1.0.0

flutter:
