name: when_async_flutter
description: Components (i.e Widgets, ChangeNotifier) for easy consumption of asynchronous computation result & snapshots.
version: 1.0.0
homepage: https://magnificsoftware.com

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  when_async: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  rational_lint: ^1.0.1+1

flutter:
