name: when_async_flutter
description: Contains widgets, notifiers, etc to work with asynchronous computations. Helps with easy consumption of such computations in a flutter widget.
version: 1.2.0+1
# https://magnificsoftware.com
homepage: https://github.com/predatorx7/flutter_packages/tree/main/when_async_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  when_async: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  rational_lint: ^1.0.1+1

flutter:
