name: when_async_flutter
description: Contains widgets, notifiers, etc to work with asynchronous computations.
version: 1.2.0
homepage: https://magnificsoftware.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  when_async: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  rational_lint: ^1.0.1+1

flutter:
