name: magnific_core
description: Common set of core utilities that a flutter app might need
version: 0.1.0
homepage: magnificsoftware.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  ansicolor: ^2.0.1
  cached_network_image: ^3.1.0+1
  device_info_plus: ^3.1.1
  flutter:
    sdk: flutter
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
