name: when_async
description: APIs for easy consumption of asynchronous computations
version: 1.1.0+1
homepage: https://magnificsoftware.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  rational_lint: ^1.0.1+1
  test: ^1.14.4
