name: when_async
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: magnificsoftware.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  rational_lint: ^1.0.1+1
  test: ^1.14.4
