name: when_async
description: Contains utility classes to work with asynchronous computations. Helps with easy consumption of such computations.
version: 1.2.2
# https://magnificsoftware.com
homepage: https://github.com/predatorx7/flutter_packages

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  rational_lint: ^1.0.1+1
  test: ^1.14.4
